# Generated by Django 4.0.2 on 2022-02-22 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('identificacion_cl', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Identificación')),
                ('tipo_id_cl', models.IntegerField(choices=[[0, 'CEDULA CIUDADANIA'], [1, 'CEDULA EXTRANGERIA'], [2, 'PASAPORTE']])),
                ('nombre_cl', models.CharField(max_length=22, verbose_name='Nombres')),
                ('apellido_cl', models.CharField(max_length=25, verbose_name='Apellidos')),
                ('correo_cl', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono_cl', models.CharField(max_length=14, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo', models.IntegerField(choices=[[0, 'Consulta'], [1, 'Reclamo'], [2, 'Sugerencia'], [3, 'Felicitación']])),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id_hb', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Num. Habitacion')),
                ('capacidad', models.PositiveIntegerField(max_length=1, verbose_name='Capacidad')),
                ('descripcion_hb', models.CharField(max_length=50, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False, verbose_name='Id. Plan')),
                ('nombre_plan', models.CharField(max_length=22, verbose_name='Nombre')),
                ('descripcion_plan', models.CharField(max_length=50, verbose_name='Descripción')),
                ('precio', models.IntegerField(verbose_name='Costo Dia')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False, verbose_name='Id. Reserva')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('id_hb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelLP.habitacion', verbose_name='Id Habitacion')),
                ('identificacion_cl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelLP.cliente', verbose_name='Id. Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='habitacion',
            name='id_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelLP.plan', verbose_name='Plan'),
        ),
    ]
