# Generated by Django 4.0.2 on 2022-02-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelLP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='foto',
            field=models.ImageField(null=True, upload_to='habitaciones', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='capacidad',
            field=models.PositiveIntegerField(verbose_name='Capacidad'),
        ),
    ]
